%YAML:1.0 # need to specify the file type at the top!

imu0:
  # camera-vicon calibration low raw
  T_cam_body:  #camera to body
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]

  # accelerometer_noise_density: 1.4e-03 #1.4e-02  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  # accelerometer_random_walk: 8.0e-05    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  #accelerometer_noise_density: 1.4e-02 #1.4e-02  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  #accelerometer_random_walk: 8.0e-04    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  #gyroscope_noise_density: 8.6e-04    # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  #gyroscope_random_walk: 2.2e-05        # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  accelerometer_noise_density: 0.0012655720309610252 
  accelerometer_random_walk: 5.6386016813618435e-05 
  gyroscope_noise_density: 0.0007294729852113113
  gyroscope_random_walk: 6.996094830870257e-06 
  #  accelerometer_noise_density: 0.1   # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  #  accelerometer_random_walk: 0.002   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  #  gyroscope_noise_density: 0.05      # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  #  gyroscope_random_walk: 4.0e-05     # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  model: calibrated
  # rostopic: /zed_nodelet/imu/data_raw_filtered
  rostopic: /imu/data
  time_offset: 0.0052559264670291456
  update_rate: 200.0
  odom_update_rate: 120.0 
