%YAML:1.0 # need to specify the file type at the top!

imu0:
  # camera-vicon calibration low raw
  T_cam_body:  #camera to body
    - [-0.00360119,  0.00865547,  0.99995606,  0.07063546]
    - [-0.99984679,  0.0170983,  -0.0037488, -0.03820127]
    - [-0.01713,    -0.99981635,  0.00859257, -0.04474833]
    - [0.0, 0.0, 0.0, 1.0]

  # accelerometer_noise_density: 1.4e-03 #1.4e-02  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  # accelerometer_random_walk: 8.0e-05    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  #accelerometer_noise_density: 1.4e-02 #1.4e-02  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  #accelerometer_random_walk: 8.0e-04    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  #gyroscope_noise_density: 8.6e-04    # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  #gyroscope_random_walk: 2.2e-05        # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  accelerometer_noise_density: 0.01
  accelerometer_random_walk: 0.0002
  gyroscope_noise_density: 0.005
  gyroscope_random_walk: 4.0e-06
  #  accelerometer_noise_density: 0.1   # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  #  accelerometer_random_walk: 0.002   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  #  gyroscope_noise_density: 0.05      # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  #  gyroscope_random_walk: 4.0e-05     # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  model: calibrated
  # rostopic: /zed_nodelet/imu/data_raw_filtered
  rostopic: /cam1/imu
  time_offset:  0.0052559264670291456
  update_rate: 400.0
  odom_update_rate: 120.0 
